project:
  type: website
  preview:
    host: "0.0.0.0" 
    port: 8765
    browser: false
website:
  favicon: favicon.png
  image: index.png
  title: "DMB"
  twitter-card:
    creator: "@lngtmknmndng_"
  open-graph: true
  navbar:
    logo: favicon.png
    pinned: true
    left: 
      - text: Beranda
        file: index.qmd
      - text: Arsip
        file: archive.qmd
      - text: Catatan
        file: notes.qmd
      - text: Tentang
        file: about.qmd
    tools:
      - icon: github
        text: Github
        href: https://github.com/deadManAlive
      - icon: twitter
        text: Twitter
        href: https://twitter.com/lngtmknmndng_
      - icon: three-dots
        text: More...
        menu:
          - text: Email
            href: "javascript:location.href = 'mailto:' + ['embryon.id','gmail.com'].join('@')"
          - text: LinkedIn
            url: https://www.linkedin.com/in/rafky-alfa
    style: docked
    alignment: center
  page-footer:
    left: "[![cc-by-sa](https://i.creativecommons.org/l/by-sa/4.0/80x15.png)](/disclaimer.qmd \"Dilisensikan oleh Muhammad Rafky Alfarrakhan.S\")"
    right: "Website ini dibangun dengan [Quarto](https://quarto.org/)."
    center:
      - icon: github
        href: https://github.com/deadManAlive
      - icon: twitter
        href: https://twitter.com/lngtmknmndng_
  search:
    type: textbox
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
format:
  html:
    theme:
      light: litera
      dark: [litera, dark.scss]
    css: styles.css
    smooth-scroll: true
    toc: true
    toc-location: right
    toc-title: Daftar Isi
    toc-depth: 5
    toc-expand: 2
    code-fold: true
    tbl-cap-location: bottom
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: true
    highlight-style: breeze
lang: id
resources:
  - "posts/**/assets/*"
  - "google85066c678af67ab6.html"
execute: 
  freeze: auto