project:
  type: website
website:
  favicon: favicon.png
  image: index.png
  title: "DMB"
  twitter-card:
    creator: "@lngtmknmndng_"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: logo.png
    pinned: true
    left: 
      - text: Beranda
        file: index.qmd
      - text: Tentang
        file: about.qmd
      - icon: three-dots
        menu:
          - text: Arsip
            file: archive.qmd
          - text: "Catatan"
            file: notes.qmd
    tools:
      - icon: github
        text: Github
        href: https://github.com/deadManAlive
      - icon: twitter
        text: Twitter
        href: https://twitter.com/lngtmknmndng_
      - icon: three-dots
        text: More...
        menu:
          - text: LinkedIn
            url: https://www.linkedin.com/in/rafky-alfa
          - text: Disclaimer
            file: disclaimer.qmd
  sidebar:
    contents:
      - section: "Laman"
        contents: 
          - text: Beranda
            file: index.qmd
          - text: Tentang
            file: about.qmd
          - text: Arsip
            file: archive.qmd
          - text: Catatan
            file: notes.qmd
    style: floating
    alignment: center
  page-footer:
    left: "@2023 Muhammad Rafky Alfarrakhan.S"
    right: "Website ini dibangun dengan [Quarto](https://quarto.org/)."
    center:
      - icon: github
        href: https://github.com/deadManAlive
      - icon: twitter
        href: https://twitter.com/lngtmknmndng_
  search:
    type: textbox
    location: sidebar
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    smooth-scroll: true
    toc: true
    toc-location: right
    toc-title: Konten
    toc-depth: 5
    code-fold: true
    tbl-cap-location: bottom
    code-line-numbers: true
    code-block-border-left: true
    highlight-style: breeze
lang: id


