<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="id" xml:lang="id"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.336">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dead Man">

<title>DMB - Musitech: 24-Bit Integer vs.&nbsp;32-Bit Floating-Point, Part II [WIP]</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Tidak ada hasil",
    "search-matching-documents-text": "dokumen cocok",
    "search-copy-link-title": "Salin tautan untuk mencari",
    "search-hide-matches-text": "Sembunyikan kecocokan lainnya",
    "search-more-match-text": "kecocokan lainnya di dokumen ini",
    "search-more-matches-text": "kecocokan lainnya di dokumen ini",
    "search-clear-button-title": "Hapus",
    "search-detached-cancel-button-title": "Batal",
    "search-submit-button-title": "Kirim"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean",
  "openSidebar": false
}
</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<style>

      .quarto-title-block .quarto-title-banner {
        background-image: url(image.jpg);
background-size: cover;
      }
</style>
<script src="../../runtime.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="DMB - Musitech: 24-Bit Integer vs.&nbsp;32-Bit Floating-Point, Part II [WIP]">
<meta property="og:description" content="">
<meta property="og:image" content="https://deadManAlive.github.io/posts/24int-vs-32float-ii/image.jpg">
<meta property="og:site-name" content="DMB">
<meta name="twitter:title" content="DMB - Musitech: 24-Bit Integer vs.&nbsp;32-Bit Floating-Point, Part II [WIP]">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://deadManAlive.github.io/posts/24int-vs-32float-ii/image.jpg">
<meta name="twitter:creator" content="@lngtmknmndng_">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">DMB</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Alihkan navigasi" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Beranda</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Tentang</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../archive.html" rel="" target="">
 <span class="menu-text">Arsip</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../notes.html" rel="" target="">
 <span class="menu-text">Catatan</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto tools-wide">
    <a href="https://github.com/deadManAlive" title="Github" class="quarto-navigation-tool px-1" aria-label="Github"><i class="bi bi-github"></i></a>
    <a href="https://twitter.com/lngtmknmndng_" title="Twitter" class="quarto-navigation-tool px-1" aria-label="Twitter"><i class="bi bi-twitter"></i></a>
    <div class="dropdown">
      <a href="" title="More..." id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="More..."><i class="bi bi-three-dots"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools ms-auto-item" href="javascript:location.href = 'mailto:' + ['embryon.id','gmail.com'].join('@')">
            Email
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools ms-auto-item" href="https://www.linkedin.com/in/rafky-alfa">
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alihkan bilah sisi" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Musitech: 24-Bit Integer vs.&nbsp;32-Bit Floating-Point, Part II [WIP]</li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alihkan bilah sisi" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Mencari" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Musitech: 24-Bit Integer vs.&nbsp;32-Bit Floating-Point, Part II [WIP]</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Musitech</div>
                <div class="quarto-category">Analisis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Penulis</div>
      <div class="quarto-title-meta-contents">
               <p>Dead Man </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Diterbitkan</div>
      <div class="quarto-title-meta-contents">
        <p class="date">12 Mei 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Mencari"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Laman</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alihkan bagian">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Beranda</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tentang</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Arsip</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Catatan</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Daftar Isi</h2>
   
  <ul>
  <li><a href="#headroom" id="toc-headroom" class="nav-link active" data-scroll-target="#headroom"><em>Headroom</em></a>
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">“<span class="math inline">\([-1,1]\)</span>”</a></li>
  <li><a href="#mubazir" id="toc-mubazir" class="nav-link" data-scroll-target="#mubazir">Mubazir?</a></li>
  </ul></li>
  <li><a href="#bit-signed-integer-vs-32-bit-floating-point" id="toc-bit-signed-integer-vs-32-bit-floating-point" class="nav-link" data-scroll-target="#bit-signed-integer-vs-32-bit-floating-point">24-Bit Signed Integer vs 32-Bit Floating-Point</a>
  <ul>
  <li><a href="#menghitung-level-kuantisasi-float32" id="toc-menghitung-level-kuantisasi-float32" class="nav-link" data-scroll-target="#menghitung-level-kuantisasi-float32">1. Menghitung level kuantisasi <code>float32</code></a></li>
  <li><a href="#level-kuantisasi-yang-digunakan-pada-sebuah-file-wav" id="toc-level-kuantisasi-yang-digunakan-pada-sebuah-file-wav" class="nav-link" data-scroll-target="#level-kuantisasi-yang-digunakan-pada-sebuah-file-wav">2. Level kuantisasi yang digunakan pada sebuah <em>file</em> WAV</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Setelah membahas sedikit tentang dasar sistem <em>floating-point</em> pada <a href="../../posts/24int-vs-32float/index.html">bagian pertama</a>, mari kita lanjutkan pembahasan secara lebih spesifik mengenai perbandingan <strong>24-bit integer</strong> vs.&nbsp;<strong>32-bit <em>floating-point</em></strong>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="&quot;24-bit vs 32-bit&quot;">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
“24-bit vs 32-bit”
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sebagai pengingat, dalam dunia musik sering kali <em>bit depth</em> hanya disebutkan nilainya, tanpa embel-embel <em>integer</em>, <em>floating-point</em>, dsb. Hal ini lumrah dilakukan karena dalam dunia audio professional, hanya 3 mode yang sering digunakan: 16 dan 24-bit <strong>integer</strong> dan 32-bit <strong>floating-point</strong> meskipun faktanya di luar itu juga terdapat 16-bit <em>floating-point</em>, 32-bit <em>integer</em>, dsb. Perhatikan <a href="https://www.youtube.com/watch?v=lwyx5mpO35Q">video berikut</a> yang tidak menyinggung <em>integer</em> ataupun <em>floating-point</em>, tetapi secara implisit membandingkan kedua tipe tersebut.</p>
</div>
</div>
</div>
<section id="headroom" class="level2">
<h2 class="anchored" data-anchor-id="headroom"><em>Headroom</em></h2>
<p>Sekilas kelebihan dari 32-bit <em>floating-point</em> yang dapat diperhatikan adalah terkait <em>headroom</em>-nya, dimana <em>floating-point</em> dapat menyimpan data dengan gain yang sangat besar bahkan hingga beberapa ratus dB di atas 0 dBFS tanpa memperkenalkan distorsi akibat <em>clipping</em> seperti yang terjadi pada tipe <em>integer</em> yang instan muncul ketika sinyal melewati 0 dB. <strong>Kenapa hal ini dapat terjadi?</strong></p>
<div class="callout callout-style-default callout-important callout-titled" title="IEEE 754">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
IEEE 754
</div>
</div>
<div class="callout-body-container callout-body">
<p>Artikel ini dan artikel <a href="../24int-vs-32float">bagian pertama</a> membatasi bahasan pada <em>floating-point</em> 32-bit yang terstandardisasi dalam IEEE 754 (IEEE <em>Standard for Floating-Point Arithmetic</em>) <code>binary32</code> (<em>single-precision floating-point format</em>), yang dalam artikel ini akan dirujuk secara bergantian sebagai “<em>floating-point</em>”, <code>float</code>, ataupun <code>float32</code>. <em>Floating-point</em> dengan lebar data lainnya, seperi <em>double-precision</em> (64-bit), memiliki struktur yang berbeda dan mungkin akan dibahas di lain kesempatan.</p>
</div>
</div>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">“<span class="math inline">\([-1,1]\)</span>”</h3>
<p>Jawaban dari pertanyaan di atas ialah meskipun format <code>float32</code> mampu menyimpan data yang sangat besar, hingga <span class="math inline">\(3.40 \times 10 ^{38}\)</span>, penggunaan <code>float32</code> pada dunia audio menggunakan nilai ternormalisasi. Dengan kata lain, dalam dunia digital audio, <strong>nilai yang digunakan hanya pada rentang</strong> <span class="math inline">\(-1\)</span> hingga <span class="math inline">\(1\)</span>, dan umumnya juga dibatasi menggunakan nilai <a href="../24int-vs-32float/#nilai-subnormaldenormal">normal</a>.</p>
<p>Apa konsekuensi dari hal ini? Dengan begitu maka 0 dBFS berada pada nilai <span class="math inline">\(-1\)</span> atau <span class="math inline">\(1\)</span>, dan dapat menyimpan nilai yang lebih besar <span class="math inline">\(3.40 \times 10 ^{38}\)</span> (<span class="math inline">\(+770\;\mathrm{dB}\)</span>) kali ataupun <span class="math inline">\(8.51 \times 10 ^{38}\)</span> kali lebih kecil (<span class="math inline">\(-759\;\mathrm{dB}\)</span>) relatif dari 0 dBFS. Sangat besar (dan kecil) dan sangat lebih dari cukup untuk mendukung rekaman audio seekstrim apa pun.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="$+770;\mathrm{dB}$??">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="math inline">\(+770;\mathrm{dB}\)</span>??
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ingin tahu dari mana angka itu muncul? Mari kita gunakan bantuan pemrograman yaitu dengan <code>Python</code> dan modul <code>numpy</code>.</p>
<p>Dimulai dengan mengimpor <code>numpy</code>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Kemudian anda dapat melihat nilai-nilai penting, seperti nilai terbesar, terkecil, <em>epsilon</em>, dsb. (<a href="https://numpy.org/doc/stable/reference/generated/numpy.finfo.html">detail</a>) dari <code>float32</code> dengan fungsi <code>np.finfo</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1"></a><span class="bu">print</span>(np.finfo(np.float32))</span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Nilai terbesar dan terkecil (relatif terhadap 0) dari informasi di atas ialah <code>max</code> dan <code>tiny</code>.</p>
<p>Selanjutnya, definisikan fungsi untuk mengkonversi nilai <em>gain</em> (<em>magnitude</em>) ke nilai desibel yang memiliki rumus <span class="math inline">\(d=20\log_{10}(M)\)</span>:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a>mag2db <span class="op">=</span> <span class="kw">lambda</span> x: <span class="dv">20</span> <span class="op">*</span> np.log10(x)</span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Gunakan <code>mag2db</code> untuk menentukan <em>range</em> desibel dari <code>float32</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1"></a><span class="bu">print</span>(mag2db(np.finfo(np.float32).<span class="bu">max</span>) <span class="co"># "770.638...", desibel maksimum</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="bu">print</span>(mag2db(np.finfo(np.float32).tiny) <span class="co"># "-758.595...", desibel minimum</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="mubazir" class="level3">
<h3 class="anchored" data-anchor-id="mubazir">Mubazir?</h3>
<p>Sebagian dari kita kemudian bertanya-tanya “kenapa hanya digunakan rentang <span class="math inline">\(-1\)</span> ke <span class="math inline">\(1\)</span> saja?”, “kenapa tidak dimaksimalkan seperti pada <em>integer</em>?”, atau “lalu apakah data yang berada diluar rentang <span class="math inline">\(-1\)</span>-<span class="math inline">\(1\)</span> akan tersia-siakan saja?”, dan sebagainya.</p>
<p>Jawabannya berada pada kata <strong><em>floating-point</em></strong> itu sendiri.</p>
<p>Bagian 1 dari <a href="../24int-vs-32float/#floating-menggantikan-fixed">artikel ini</a> telah membahas cara kerja <code>float</code> yang menunjukkan bahwa posisi desimal (koma) pada bilangan float bersifat tidak tetap (<em>floating</em>), berbeda dengan tipe data <em>fixed-point</em>. Pada representasi <code>float</code> selalu hanya ada satu digit di depan koma (pada mode <strong>normal</strong> selalu bernilai <code>1</code> dan implisit), dan nilai yang berbeda direpresentasikan dengan nilai eksponen dan koefisien/<em>mantissa</em> yang berbeda.</p>
<p>Sebagai contoh, karena hanya 1 digit di depan koma, maka <code>float</code> tidak dapat menyimpan <code>1011.001</code> secara langsung, tetapi bentuk tersebut dapat diubah ke <code>1.011001 * 10101</code> (atau <span class="math inline">\(2^3\)</span> dalam desimal) yang dapat disimpan oleh <code>float</code>. Mekanisme seperti ini lah yang membuat <code>float</code> dapat menyimpan angka yang sangat besar dan sangat kecil. Tetapi disamping itu, terdapat satu hal yang menjadi konsekuensi hal di atas: <strong>semakin kecil angka yang direpresentasikan <code>float</code>, semakin tinggi resolusinya</strong>. Sehingga digunakanlah nilai ternormalisasi pada rentang <span class="math inline">\([-1,1]\)</span> untuk memaksimalkan resolusi sinyal.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Tinggi dan Berat">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tinggi dan Berat
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Untuk mempermudah, mari kita analogikan dengan bilangan desimal. Misalkan anda sedang mengisi isian biodata untuk sebuah pendaftaran, dan kemudian anda sampai pada isian tinggi badan. Pada formulir ini, diberikan 6 kotak untuk mengisi angka tinggi badan, dengan catatan semua kotak harus terisi tetapi anda bebas untuk meletakkan dimana posisi koma, apakah di antara kotak 1 dan 2, 2 dan 3, dan seterusnya.</p>
<p>Misalkan tinggi badan anda adalah tepat <span class="math inline">\(174\)</span> cm, maka anda akan mengisi <span class="math inline">\(174.000\)</span> pada isian tersebut dan meletakkan koma antara kotak 3 dan 4. Pertanyaannya adalah, jika angka paling kanan diubah 1 digit, berapakah perubahan yang terjadi pada angka? Pada isian anda, misalkan angka terkakhir diubah 1 sehingga menjadi <span class="math inline">\(174.001\)</span>, maka perubahan angka yang terjadi ialah <span class="math inline">\(0.001\)</span>. Nilai tersebut merupakan perubahan terkecil yang masih dapat direkam oleh isian 6 kotak tersebut, dalam matematika sering disebut sebagai <strong>epsilon</strong> (<span class="math inline">\(\varepsilon\)</span>)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p><span class="math display">\[
\boxed{1}\boxed{7}\boxed{4},\boxed{0}\boxed{0}\boxed{0}
\]</span></p>
<p>Bagaimana jika selanjutnya dengan aturan yang sama, anda diperintahkan mengisi isian berat badan? Misalkan kali ini anda dengan lebih detail mengetahui berat anda <span class="math inline">\(89.5\)</span> kg, maka isian kotak anda ialah <span class="math inline">\(89.5000\)</span>. Perhatikan bahwa kali ini, <span class="math inline">\(\varepsilon\)</span> menjadi <span class="math inline">\(10\)</span> kali lebih kecil (<span class="math inline">\(0.0001\)</span>) dengan posisi desimal yang berubah satu tempat. <span class="math inline">\(\varepsilon\)</span> yang semakin kecil menunjukkan nilai yang semakin presisi.</p>
<p><span class="math display">\[
\boxed{8}\boxed{9},\boxed{5}\boxed{0}\boxed{0}\boxed{0}
\]</span></p>
</div>
</div>
</div>
<p>Lalu kenapa tidak digunakan <a href="../24int-vs-32float/#nilai-subnormaldenormal">nilai subnormal</a> untuk merepresentasikan nilai tersebut? Angka yang direpresentasikan diantara <span class="math inline">\(-1\)</span> dan <span class="math inline">\(1\)</span> sehingga wajar menggunakan subnormal yang diawali dengan <span class="math inline">\(0.\)</span> bukan? Jawababnya adalah karena nilai pada rentang <strong><em>subnormal</em></strong> <strong>memiliki performa pemrosesan yang lebih lambat</strong><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Bahkan, sering kali dalam beberapa kondisi yang membutuhkan performa lebih, rentang subnormal dapat saja dinonaktifkan (sebagai contoh dalam algoritma pemrosesan VST<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>)</p>
</section>
</section>
<section id="bit-signed-integer-vs-32-bit-floating-point" class="level2">
<h2 class="anchored" data-anchor-id="bit-signed-integer-vs-32-bit-floating-point">24-Bit Signed Integer vs 32-Bit Floating-Point</h2>
<p>Kembali ke pertanyaan pemicu dari seri artikel ini, “Seberapa jauh perbedaan kualitas 24-bit int dengan 32-bit FP?”. Sekilas, cukup dari lebar data kita bisa saja menyebut bahwa <code>float32</code> memiliki resolusi sebesar <span class="math inline">\(2^{31-23} = 256\)</span> kali resolusi <code>int24</code>. Tetapi, mengingat aturan representasi pada <code>float</code> tidak sesederhana pada <code>int</code>, maka kita akan mencoba menghitung level kuantisasi pada masing-masing tipe, dimana kualitas dari tipe data pembawa sinyal dapat dilihat dari jumlah level kuantisasi ini (divisualisasikan di <a href="../fs-vs-bd/#fig-adc">laman ini</a>, yang pada jenis data <strong>integer</strong> memiliki hubungan <span class="math inline">\(N=2^b\)</span> dengan <span class="math inline">\(N\)</span> jumlah level kuantisasi dan <span class="math inline">\(b\)</span> bit-depth.</p>
<p>Dari sini, dapat kita ketahui untuk tipe 24-bit integer, yang dalam dunia audio menggunakan data type <code>unsigned int</code>, memiliki nilai <span class="math inline">\(0\)</span> atau <span class="math inline">\(-\infty\;\mathrm{dB}\)</span> sebagai nilai minimum dan <span class="math inline">\(2^{23}-1=8388607\)</span> sebagai nilai maksimum (<span class="math inline">\(0\;\mathrm{dB}\)</span>). <span class="math inline">\(8 388 607\)</span> adalah jumlah level kuantisasi pada satu sisi gelombang pada <code>int24</code>, di sini dapat disebut sebagai resolusinya.</p>
<p>Bagaimana dengan <code>float</code>? Karena aturannya yang lebih rumit dan rentang yang dibatasi <span class="math inline">\(\pm 1\)</span>, maka kita akan mengunakan bantuan pemrograman, kali ini dengan bahasa pemrograman <code>rust</code> yang mempermudah manipulasi tipe data <code>float</code> (<code>f32</code>). Kita akan mencoba melakukan beberapa pengujian terhadap <code>float32</code> dan <code>int24</code>.</p>
<section id="menghitung-level-kuantisasi-float32" class="level3">
<h3 class="anchored" data-anchor-id="menghitung-level-kuantisasi-float32">1. Menghitung level kuantisasi <code>float32</code></h3>
<p>Seperti pada <code>int24</code> di atas, kita akan menghitung resolusi satu sisi (<span class="math inline">\(0\)</span> ke <span class="math inline">\(+1\)</span>), dilambangkan <span class="math inline">\(N_{Q_{[\mathrm{Nmin},1]}}\)</span>.</p>
<p>Program dimulai dengan definisi <code>start</code> dan <code>stop</code> yang menyimpan data biner masing-masing nilai normal terkecil dan satu<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, dalam bentuk biner dan direpresentasikan dalam notasi heksadesimal.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb5-1"><a href="#cb5-1"></a><span class="kw">let</span> start <span class="op">=</span> <span class="dv">0x00800000</span><span class="op">;</span> <span class="co">// == 0b00000000_10000000_00000000_00000000 == 1.175494e-38</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="kw">let</span> stop  <span class="op">=</span> <span class="dv">0x3f800000</span><span class="op">;</span> <span class="co">// == 0b00111111_10000000_00000000_00000000 == 1.0</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-note callout-titled" title="kenapa `0x00800000`?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
kenapa <code>0x00800000</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Karena pada aplikasinya, terutama dalam pemrosesan audio, rentang dibawah itu (<a href="../24int-vs-32float/#nilai-subnormaldenormal">subnormal</a>) dinonaktifkan atau dianggap 0 karena alasan performa<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p>
</div>
</div>
<p>Selanjutnya, masing-masing representasi biner tersebut di<em>cast</em> menjadi bilangan <code>float32</code> dengan memanfaatkan <em>method</em> <code>from_bits</code> dari tipe <code>f32</code><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb6-1"><a href="#cb6-1"></a><span class="kw">let</span> fstart <span class="op">=</span> <span class="dt">f32</span><span class="pp">::</span>from_bits(start)<span class="op">;</span> <span class="co">// == 1.175494e-38</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="kw">let</span> fstop  <span class="op">=</span> <span class="dt">f32</span><span class="pp">::</span>from_bits(stop)<span class="op">;</span>  <span class="co">// == 1.0</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Kemudian variable <code>step</code> dan <code>current</code> digunakan untuk masing-masing menghitung jumlah level dan menyimpan nilai level sementara:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">let</span> <span class="kw">mut</span> step<span class="op">:</span> <span class="dt">usize</span> <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="kw">let</span> <span class="kw">mut</span> current <span class="op">=</span> fstart<span class="op">;</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Perhitungan dilakukan dengan memanfaatkan method <code>next_up</code> dari tipe <code>f32</code> yang memberikan nilai <code>f32</code> selanjutnya yang dapat direpresentasikan oleh data tersebut<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. Menggunakan <em>loop</em> <code>while</code>, program menghitung jumlah nilai-nilai yang mungkin antara <code>fstart</code> dan <code>fstop</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb8-1"><a href="#cb8-1"></a><span class="cf">while</span> current <span class="op">&lt;</span> fstop <span class="op">{</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>    step <span class="op">+=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>    current <span class="op">=</span> current<span class="op">.</span>next_up()<span class="op">;</span></span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="op">}</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Selanjutnya kita gunakan kode berikut untuk menampilkan jumlah step yang kita cari, disamping nilai awal dan nilai akhir yang telah ditentukan:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb9-1"><a href="#cb9-1"></a><span class="pp">println!</span>(<span class="st">"start: u32 {} f32 {:e}"</span><span class="op">,</span> start<span class="op">,</span> fstart)<span class="op">;</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="pp">println!</span>(<span class="st">"stop: u32 {} f32 {:e}"</span><span class="op">,</span> stop<span class="op">,</span> fstop)<span class="op">;</span></span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="co">// ...</span></span>
<span id="cb9-4"><a href="#cb9-4"></a><span class="pp">println!</span>(<span class="st">"There's {} level between {:e} and {:e}"</span><span class="op">,</span> step<span class="op">,</span> fstart<span class="op">,</span> fstop)<span class="op">;</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Maka program akan memberikan output:</p>
<pre data-code-line-numbers="false"><code>start: u32 8388608 f32 1.1754944e-38
stop: u32 1065353216 f32 1e0
There's 1056964608 level between 1.1754944e-38 and 1e0</code></pre>
<p>Dapat dilihat bahwa terdapat <span class="math inline">\(1056964608\)</span> level antara nilai tengah (digantikan nilai normal minimum disini) dengan nilai maksimum (<span class="math inline">\(1.0\)</span>). Sementara, <code>int24</code> memberikan nilai <span class="math inline">\(8388608\)</span> sehingga terdapat rasio perbedaan sebesar <span class="math inline">\(126\)</span>, meleset <span class="math inline">\(2\)</span> (dari <span class="math inline">\(256\)</span>) kali lipat jika dihitung secara sederhana dari perbedaan jumlah bit kedua tipe data tersebut.</p>
<div class="callout callout-style-default callout-note callout-titled" title="$8388608$">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="math inline">\(8388608\)</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Not hehe.</p>
</div>
</div>
</div>
<p><span class="math inline">\(126\)</span> kali lipat bukanlah rasio yang kecil untuk perbandingan resolusi, sebagai contoh perbandingan resolusi gambar dengan membandingkan jumlah <em>pixel</em> <strong>4K</strong> (<span class="math inline">\(3840\times2160\)</span>) dengan <strong>360p</strong> (<span class="math inline">\(640\times360\)</span>) hanya mencapai <span class="math inline">\(36\)</span> kali, hampir 4 kali lebih kecil dari perbandingan resolusi <code>float32</code> dan <code>int24</code>, dan tentu pembaca tahu bagaimana perbedaan kualitas antara 4K dengan 360p.</p>
<div id="fig-res-comp" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-4k" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./4kx.jpg" class="img-fluid figure-img" data-ref-parent="fig-res-comp"></p>
<figcaption class="figure-caption">(a) 4K</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-360p" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./sdx.jpg" class="img-fluid figure-img" data-ref-parent="fig-res-comp"></p>
<figcaption class="figure-caption">(b) 360p</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Gambar&nbsp;1: 4K vs.&nbsp;360p (Buka di tab baru jika gambar terlalu kecil)</figcaption><p></p>
</figure>
</div>
<blockquote class="blockquote">
<p><strong>Kesimpulan 1</strong>: Sebuah sinyal <code>float32</code> akan memiliki resolusi <strong>126 kali</strong> resolusi sinyal <code>int24</code>.</p>
</blockquote>
</section>
<section id="level-kuantisasi-yang-digunakan-pada-sebuah-file-wav" class="level3">
<h3 class="anchored" data-anchor-id="level-kuantisasi-yang-digunakan-pada-sebuah-file-wav">2. Level kuantisasi yang digunakan pada sebuah <em>file</em> WAV</h3>
<p>Selanjutnya, mari lakukan analisis dari sisi praktis, yaitu dengan menghitung jumlah level yang terpakai pada sebuah <em>file</em> WAV. Pertanyaannya adalah apakah sebuah <em>file</em> <code>float32</code> akan menggunakan semua <span class="math inline">\(2\times1056964608\approx2.113\times10^9\)</span> dan apakah <em>file</em> <code>int24</code> akan menggunakan semua <span class="math inline">\(2^{24}=16,777,216\)</span>?</p>
<p>Langkah dalam melakukan percobaan ini ialah dengan membuka sebuah <em>file</em> WAV, lalu menyimpan setiap nilai titik <em>sample</em> ke sebuah <em>set</em> yang hanya menyimpan nilai yang unik dan kemudian menghitung jumlah elemen pada <em>set</em> tersebut untuk menemukan jumlah level yang digunakan oleh masing-masing format. Karena perbandingan sesama bilangan float merupakan hal yang rumit<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>, maka kita gunakan represenasi binernya dalam bentuk <code>int32</code>.</p>
<p>Program menggunakan <code>std::collections::HashSet</code> dari <em>standard library</em> untuk struktur data <em>set</em> yang dibutuhkan dan <em>crate</em> <code>wav</code> untuk mempermudah pembacaan <em>file</em> WAV.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb11-1"><a href="#cb11-1"></a><span class="kw">use</span> <span class="pp">std::</span><span class="op">{</span><span class="pp">collections::</span>HashSet<span class="op">,</span> <span class="pp">fs::</span>File<span class="op">,</span> <span class="pp">path::</span><span class="dt">Path</span><span class="op">};</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="kw">use</span> <span class="pp">wav::</span>BitDepth<span class="op">;</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Misalkan <em>file</em> bernama “sound.wav”, maka selanjutnya data dan <em>header</em> (yang berisi informasi seperti <em>sample rate</em>, <em>bit depth</em>, dsb.) dapat dibaca dengan cara berikut:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb12-1"><a href="#cb12-1"></a><span class="kw">let</span> filename <span class="op">=</span> <span class="st">"sound.wav"</span><span class="op">;</span></span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="kw">let</span> <span class="kw">mut</span> sound <span class="op">=</span> <span class="pp">File::</span>open(<span class="dt">Path</span><span class="pp">::</span>new(filename))<span class="op">?;</span></span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="kw">let</span> (header<span class="op">,</span> data) <span class="op">=</span> <span class="pp">wav::</span>read(<span class="op">&amp;</span><span class="kw">mut</span> sound)<span class="op">?;</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Jangan lupa deklarasikan <em>set</em> yang akan digunakan:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb13-1"><a href="#cb13-1"></a><span class="kw">let</span> <span class="kw">mut</span> set <span class="op">=</span> <span class="pp">HashSet::</span>new()<span class="op">;</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Selanjutnya, sesuai dengan cara kerja <em>crate</em> wav dimana variable <code>data</code> yang didapat dari <em>method</em> <code>wav::read</code> adalah sebuah <strong>enumerasi</strong> <em>bit depth</em>, maka kita akan melakukan <em>pattern matching</em>, dalam hal ini kita hanya peduli dengan <code>ThirtyTwoFloat</code> sebagai <code>float32</code> dan <code>TwentyFour</code> sebagai <code>int24</code>:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb14-1"><a href="#cb14-1"></a><span class="cf">match</span> data <span class="op">{</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>  <span class="pp">BitDepth::</span>ThirtyTwoFloat(v) <span class="op">=&gt;</span> <span class="op">{</span> <span class="co">/* proses tipe float32 dalam v */</span><span class="op">},</span></span>
<span id="cb14-3"><a href="#cb14-3"></a>  <span class="pp">BitDepth::</span>TwentyFour(v) <span class="op">=&gt;</span> <span class="op">{</span><span class="co">/* proses int24 */</span><span class="op">},</span></span>
<span id="cb14-4"><a href="#cb14-4"></a>  _ <span class="op">=&gt;</span> <span class="op">{</span><span class="co">/* abaikan bit depth lainnya */</span><span class="op">},</span></span>
<span id="cb14-5"><a href="#cb14-5"></a><span class="op">}</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Pada <code>ThirtyTwoFloat</code>, kita hanya perlu melakukan insersi data <em>sample</em> yang telah dikonversi ke bentuk biner dalam tipe <code>u32</code> yang diperoleh dengan <em>method</em> <code>f32::to_bits</code>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb15-1"><a href="#cb15-1"></a><span class="co">// ...</span></span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="pp">BitDepth::</span>ThirtyTwoFloat(v) <span class="op">=&gt;</span> <span class="op">{</span></span>
<span id="cb15-3"><a href="#cb15-3"></a>  <span class="cf">for</span> sample <span class="kw">in</span> v <span class="op">{</span></span>
<span id="cb15-4"><a href="#cb15-4"></a>    set<span class="op">.</span>insert(sample<span class="op">.</span>to_bits())<span class="op">;</span></span>
<span id="cb15-5"><a href="#cb15-5"></a>  <span class="op">}</span></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="op">},</span></span>
<span id="cb15-7"><a href="#cb15-7"></a><span class="co">// ...</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Semantara itu, pada <code>TwentyFour</code>, kita perlu menyentuh <code>unsafe</code> karena data yang dibaca adalah <code>i32</code>, sementara untuk menyamai dengan <em>case</em> di atas, <code>HashSet</code> yang kita gunakan hanya akan menerima <code>u32</code>, untuk itu kita akan melakukan konversi <code>transmute</code> pada Rust yang harus dilakukan dalam blok <code>unsafe</code>:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb16-1"><a href="#cb16-1"></a><span class="co">// ...</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="pp">BitDepth::</span>TwentyFour(v) <span class="op">=&gt;</span> <span class="op">{</span></span>
<span id="cb16-3"><a href="#cb16-3"></a>    <span class="cf">for</span> sample <span class="kw">in</span> v <span class="op">{</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>        <span class="kw">let</span> as_u32<span class="op">:</span> <span class="dt">u32</span><span class="op">;</span></span>
<span id="cb16-5"><a href="#cb16-5"></a></span>
<span id="cb16-6"><a href="#cb16-6"></a>        <span class="kw">unsafe</span> <span class="op">{</span></span>
<span id="cb16-7"><a href="#cb16-7"></a>            as_u32 <span class="op">=</span> <span class="pp">mem::</span>transmute(sample)<span class="op">;</span></span>
<span id="cb16-8"><a href="#cb16-8"></a>        <span class="op">}</span></span>
<span id="cb16-9"><a href="#cb16-9"></a></span>
<span id="cb16-10"><a href="#cb16-10"></a>        set<span class="op">.</span>insert(as_u32)<span class="op">;</span></span>
<span id="cb16-11"><a href="#cb16-11"></a>    <span class="op">}</span></span>
<span id="cb16-12"><a href="#cb16-12"></a><span class="op">},</span></span>
<span id="cb16-13"><a href="#cb16-13"></a><span class="co">// ...</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Terakhir, setelah melakukan proses di atas dalam <em>pattern matching</em>, informasi-informasi yang didapatkan dapat ditampilkan kurang lebih seperti:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode numberSource rust number-lines code-with-copy"><code class="sourceCode rust"><span id="cb17-1"><a href="#cb17-1"></a><span class="pp">println!</span>(</span>
<span id="cb17-2"><a href="#cb17-2"></a>    <span class="st">"'{}' (format: {}, channels: {}, sampling rate: {} Hz, bit depth: {} bits) has {} uniques samples"</span><span class="op">,</span></span>
<span id="cb17-3"><a href="#cb17-3"></a>    filename<span class="op">,</span></span>
<span id="cb17-4"><a href="#cb17-4"></a>    header<span class="op">.</span>audio_format<span class="op">,</span></span>
<span id="cb17-5"><a href="#cb17-5"></a>    header<span class="op">.</span>channel_count<span class="op">,</span></span>
<span id="cb17-6"><a href="#cb17-6"></a>    header<span class="op">.</span>sampling_rate<span class="op">,</span></span>
<span id="cb17-7"><a href="#cb17-7"></a>    header<span class="op">.</span>bits_per_sample<span class="op">,</span></span>
<span id="cb17-8"><a href="#cb17-8"></a>    set<span class="op">.</span>len()</span>
<span id="cb17-9"><a href="#cb17-9"></a>)<span class="op">;</span></span></code><button title="Salin ke Papan Klip" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Kode di atas akan menampilkan nama <em>file</em>, audio format (<span class="math inline">\(1\)</span> untuk <code>int</code>, <span class="math inline">\(3\)</span> untuk <code>float</code>), <em>sampling rate</em>, <em>bit depth</em> dan jumlah level yang digunakan yang kita cari. Sebagai contoh:</p>
<pre data-code-line-numbers="false"><code>'sound.wav' (format: 3, channels: 1, sampling rate: 44100 Hz, bit depth: 32 bits) has 485123 uniques samples</code></pre>
<p>Untuk analisis ini, penulis melakuka pengujian pada beberapa <em>file</em> audio dengan format dan sinyal yang berbeda untuk melihat perbandingan level yang digunakan (“XXX” pada nama <em>file</em> berarti “f32” atau “i24” tergantung fotmat):</p>
<div id="tbl-prc-cmp" class="anchored">
<table class="table">
<caption>Tabel&nbsp;1: Perbandingan beberapa <em>file</em> WAV (dalam jumlah level yang digunakan)</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Nama File</th>
<th>Level <code>float32</code></th>
<th>Level <code>int24</code></th>
<th>Keterangan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>s1024XXX.wav</em></td>
<td>219876</td>
<td>219249</td>
<td><em>pure</em> 1024 Hz <em>sine</em>, 44.1 kHz</td>
</tr>
<tr class="even">
<td><em>nXXX.wav</em></td>
<td>220131</td>
<td>217022</td>
<td><em>white noise</em>, 44.1 kHz</td>
</tr>
<tr class="odd">
<td><em>s1024XXX-192k.wav</em></td>
<td>947845</td>
<td>935675</td>
<td><em>pure</em> 1024 Hz <em>sine</em>, 44.1 kHz</td>
</tr>
<tr class="even">
<td><em>nXXX-192k.wav</em></td>
<td>953713</td>
<td>642765</td>
<td><em>white noise</em>, 44.1 kHz</td>
</tr>
</tbody>
</table>
</div>
<p>Sekilas dapat kita lihat dari jumlah level yang digunakan, <em>sample rate</em> lebih berpengaruh dari pada <em>bit depth</em>, <code>float32</code> dan <code>int24</code> juga menggunakan jumlah level yang relatif sama pada <em>sample rate</em> yang sama. Bahkan, bentuk sinyal, meskipun sama-sama minimal dibanding dengan <em>sample rate</em>, lebih berpengaruh terhadap jumlah level yang digunakan ketimbang <em>bit depth</em>.</p>
<p>Nilai-nilai di atas tidak memberikan gambaran terhadap kualitas tetapi lebih ke peluang suatu <em>sample</em> untuk berada di nilai yang berbeda dan seharusnya semakin tinggi resolusi yang tersedia, semakin kecil peluang satu <em>sample</em> memiliki nilai yang sama dengan sample lainnya, terutama pada <em>sample</em> acak dan natural, seperti musik.</p>
<p>Yang menarik bagi penulis, dan mungkin juga sebagaian dari pembaca, adalah nilai level yang digunakan oleh <code>int24</code> pada <em>white noise</em> dengan <em>sample rate</em> 192 kHz, kenapa terjadi <em>drop</em> level yang sangat signifikan, hingga lebih dari 30% dibanding <code>float32</code>? Sekali lagi, nilai-nilai ini tidak berkorelasi sama sekali dengan kualitas tetapi peluang untuk kejadian tersebut cukup menarik.</p>
<p>Kesalahan algoritma? Penulis kemudian melakuan uji coba terhadap algoritma dengan cara mengambil sebuah <a href="https://soundcloud.com/virtual-riot/4-producers-1-sample-pn35a-virtual-riot-remix-free-download"><em>file</em></a> WAV 16-bit yang sudah ada, kemudian melakukan konversi <em>bit depth</em> dari <em>file</em> tersebut ke <code>float32</code> dan <code>int24</code>. Karena data sinyal telah terkuantisasi dari rekaman 16-bit, level yang digunakan oleh konversi <code>float32</code> dan <code>int24</code> dari <em>file</em> tersebut seharusnya memberikan nilai yang sama dan berada di sekitar <span class="math inline">\(2^{16}=65536\)</span>. Dan benar, dari <em>file</em> didapatkan keluaran berikut:</p>
<pre data-code-line-numbers="false"><code>'pn35a-f32.wav' (..., 44100 Hz, bit depth: 32 bits) has 65536 uniques samples
'pn35a-i24.wav' (..., 44100 Hz, bit depth: 24 bits) has 65536 uniques samples</code></pre>
<!-- ??? -->


</section>
</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Kembali ke atas</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Catatan Kaki</h2>

<ol>
<li id="fn1"><p>Istilah yang lebih tepat disini sebenarnya ialah <a href="https://en.wikipedia.org/wiki/Unit_in_the_last_place"><strong>ulp</strong></a> atau <em>unit of least precision</em>, tetapi untuk tidak memperkeruh istilah, mari gunakan saja <span class="math inline">\(\varepsilon\)</span> yang pada beberapa kondisi berkorespondensi terhadap <strong>ulp</strong> sebagai hal yang sama.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="https://en.wikipedia.org/wiki/Subnormal_number#Performance_issues" class="uri">https://en.wikipedia.org/wiki/Subnormal_number#Performance_issues</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="https://docs.juce.com/master/classScopedNoDenormals.html" class="uri">https://docs.juce.com/master/classScopedNoDenormals.html</a>, sebuah fitur <em>high-level</em> untuk menonaktifkan subnormal pada CPU untuk sementara pada JUCE, framework yang dapat digunakan untuk memprogram VST. Mekanisme dasarnya sendiri dapat dilihat di <a href="https://en.wikipedia.org/wiki/Subnormal_number#Disabling_subnormal_floats_at_the_code_level">sini</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Notable_single-precision_cases" class="uri">https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Notable_single-precision_cases</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><a href="https://en.wikipedia.org/wiki/Subnormal_number#Performance_issues" class="uri">https://en.wikipedia.org/wiki/Subnormal_number#Performance_issues</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><a href="https://doc.rust-lang.org/std/primitive.f32.html#method.from_bits" class="uri">https://doc.rust-lang.org/std/primitive.f32.html#method.from_bits</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><em>Method</em> <code>f32::next_up</code> hingga waktu penulisan artikel ini masih berstatus eksperimental sehingga dibutuhkan <code>rust</code> versi <strong><em>nightly</em></strong> untuk dapat menggunakannya: <a href="https://doc.rust-lang.org/std/primitive.f32.html#method.next_up" class="uri">https://doc.rust-lang.org/std/primitive.f32.html#method.next_up</a><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>error pembulatan, batasan representasi, toleransi perbandingan, hingga algoritma membuat perbandingan dua nilai <code>float</code> menjadi tidak pasti dan dalam pemrograman tidak dianjurkan (dianjurkan perbandingan dengan nilai toleransi yang ditentukan), <a href="https://floating-point-gui.de/errors/comparison/" class="uri">https://floating-point-gui.de/errors/comparison/</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Disalin!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Disalin!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><a href="../../disclaimer.html" title="Dilisensikan oleh Muhammad Rafky Alfarrakhan.S"><img src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" class="img-fluid" alt="cc-by-sa"></a></div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/deadManAlive">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/lngtmknmndng_">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">Website ini dibangun dengan <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>